service: my-express-application
 
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1	
 
functions:
  handler:
    handler: index.handler
    events:
      - http: 
          path: /post
          method: post
          cors: 
            origin: '*'
            headers:
              - Access-Control-Allow-Credentials
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
